### PR TITLE
fix(sparrow): reconcile takes the DeliveryAttempt, not bare ids

### PR DESCRIPTION
**Pull request by qingyun-wu**
## What

`DeliveryProvider.reconcile(item_id, idempotency_key)` → `reconcile(attempt: DeliveryAttempt)` where the frozen attempt carries `item_id`, `payload`, and `idempotency_key`.

**Why**: the old signature could not express reconciliation-by-safe-resend. A keyed-dedup provider whose only receipt store IS the send (the AG2 Space rid-dedup case, measured on prod during #3110) has no way to reconcile without the payload — the core had to special-case it with the `elif idempotent_send: re-attempt` branch. The cloud delivery doc adopted this as amendment 1 (ag2space-backend#687, executed under backend#683): the doc's shape is right, Sparrow's contract corrects to match.

## Evidence

- **New contract case** `test_reconcile_by_safe_resend_uses_the_attempt_payload`: the previously inexpressible provider shape, pinned — reconcile re-offers the attempt's own payload under the attempt's own key, and both offers carry one dedup identity.
- **Invariant preserved, not exempted**: the enforcement suite's derived-key scan now looks *through* the `DeliveryAttempt(...)` constructor to the key inside it. **Mutation-tested**: `DeliveryAttempt(item_id, payload, "raw-key")` in core goes red; the derived form green.
- Both core suites green; `sparrow-result-guard` green; ruff clean; `review-checks.sh` PASS on the diff.

## Interaction with open PRs

Providers in the open chain (#3110's `AG2SpaceResultProvider`, #3095's Discord provider) either omit reconcile capability-gated or implement it — their one-line adaptations ride the chain rebases; I'll patch each branch when this lands. The behavior of every existing capability path (`reconcile_capable`, `idempotent_send` fallback, park-on-neither) is unchanged — this is a signature correction, pinned by the pre-existing contract cases running unmodified.

Signed: @sutando-qingyun-001:ag2.space

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by qingyun-wu** [comment]
Approval signal on exact head `cd2ded6f9da783e0fb404a338c2b5aaedf9fdfdc`: no blocking findings.

Passing the immutable `DeliveryAttempt` gives provider-specific reconciliation the stable item id, payload, and idempotency key it needs without exposing claim-incarnation material. The core still capability-gates reconciliation, while the generic resend path remains separately gated by `idempotent_send`. I ran the full delivery-core contract and enforcement suites plus required review checks; all passed.

Reviewed by Qingyun's Personal Codex.

File: packages/ag2-sparrow/ag2_sparrow/delivery_core/core.py [hunk 1]
```diff
@@ -64,7 +64,8 @@ def deliver_one(self, item_id: str, payload: bytes) -> DrainResult:
         if outcome is DeliveryOutcome.OUTCOME_UNKNOWN:
             caps = self.provider.capabilities
             if caps.reconcile_capable:
-                resolved = self.provider.reconcile(item_id, key)
+                resolved = self.provider.reconcile(
```
Comment (qingyun-wu) [inline packages/ag2-sparrow/ag2_sparrow/delivery_core/core.py]: **Blocking:** this new call is outside the typed outcome classifier. The PR explicitly enables reconciliation by safe resend, and its test implementation does that by calling `deliver()` again; if that second send raises `ProviderIndeterminate` (or `ProviderRefused`), the exception escapes before `backend.complete()`, leaving the live claim owned indefinitely at zero attempts. A reviewer control at this head printed `ProviderIndeterminate True 0` for `(exception, successor still blocked, attempts)`. Please classify typed failures from reconciliation through the same outcome rules and add the second-ambiguous/refused cases so the claim always reaches a recoverable or terminal transition.

**Review by qingyun-wu — COMMENTED** [review]
Changes requested on exact head `cd2ded6f9da783e0fb404a338c2b5aaedf9fdfdc`. One blocking delivery-liveness issue remains. The focused 24-case contract suite, 14-case enforcement suite, Sparrow result guard, and repository review checks otherwise pass. Formal REQUEST_CHANGES is unavailable because this review identity is also the PR author.

Reviewed by Qingyun's Personal Codex.

**Comment by sonichi** [comment]
Your red CI is **not your diff** — it's the known flake in #3112. The check name doesn't say so, and it took three hops to find, so here's the chain:

```
check    tsc + tests (clean install)          fail 17m48s
step     Run shell standalone tests           (job 95795150189, step 17)
suite    tests/graceful-restart.test.sh       1 FAILURE(S)
case     10. A holder that LOSES its lease must defer, not restart alongside the reaper
         FAIL: 2 restart decisions after a lease loss
```

Two other suites also failed in that step — `sutando-migrate.test.sh` and `sync-workspace.test.sh` — but both are in `tests/shell-ci-known-failures.txt`, so they print and do not gate. `graceful-restart.test.sh` is not on that list, which is why it alone turned the job red.

Grounds for calling it unrelated rather than yours: this PR changes `reconcile`'s argument on the sparrow side, and the failing case is a shell restart-lock race; `main` ran the same suite green at 16:46, 17:12, 17:37 and 18:07 today. That is evidence, not proof — I did not re-run the suite myself — but it matches #3112's description exactly.

A re-run should clear it. Worth noting the reporting gap independently: the step exits 1 while its own tally prints `FAILED: 0` (that tally belongs to a different step), and the `::error::FAILED:` line never fires for shell suites, so nothing in the check summary or the step's last lines names the suite that gated the build. Anyone hitting this has to read 23,000 lines of log to learn which test failed.

**Comment by sonichi** [comment]
**Correcting my own last paragraph.** The diagnosis above stands — your red is #3112's `graceful-restart.test.sh` lease-loss flake, not your diff — but I described the reporting mechanism wrongly, so here it is measured rather than inferred.

I wrote that "the step exits 1 while its own tally prints `FAILED: 0` (that tally belongs to a different step)". Both halves are wrong. Those `FAILED: 0` lines are printed *inside* the shell step, by individual suites reporting their own tallies:

```
23410  → tests/start-cli-claude-config-dir.test.sh
23416  FAILED: 0                                   <- that suite's tally, not the step's
```

The step itself keeps `failed` as a shell variable and never prints a tally at all.

I also said `::error::FAILED:` "never fires for shell suites", which implied the shell step has such a line that failed to fire. It doesn't have one. Two separate steps:

```
22613  ##[group]Run failed=0   python3 loop  -> emits ::error::FAILED: $f
23269  ##[group]Run failed=0   shell loop    -> emits ✖ shell test failed: $f
```

And the shell step **does** name its failing suites — `✖ shell test failed:` fired three times, at 23317, 23447 and 23465. My "nothing names the gating suite" was simply false about the step log.

What actually survives is narrower: the shell loop emits no GitHub `::error::` annotation where the Python loop does, so the failing suite appears in the log but never in the check summary. That asymmetry is real and is why this took log-diving. It is not "no test is named".

Sorry for the noise on your PR — the wrong half was mine and I would rather correct it here than leave it for someone to act on.

**Review by yixuan-ag2 — APPROVED** [review]
Approving at `cd2ded6f`. The signature correction is right and, within this repo, complete.

## Verified rather than read

Every `DeliveryProvider.reconcile` implementer and its one caller are converted — I grepped the whole tree rather than trusting the diff's file list:

```
contract.py:225                          def reconcile(self, attempt: DeliveryAttempt)   protocol
core.py:67                               provider.reconcile(DeliveryAttempt(...))        only caller
tests/delivery-core-contract.test.py     :59, :225   updated
tests/delivery-core-enforcement.test.py  :63, :200   updated
skills/.../reconcile_launchd.py:92       unrelated function, different namespace
```

No stragglers. `DeliveryAttempt` is frozen, and threading `payload` through it is the right call — the old `(item_id, key)` shape genuinely could not express reconcile-by-safe-resend, and your new contract case pins exactly that.

## The red check is not yours

Three shell suites failed; two of them (`sutando-migrate`, `sync-workspace`) print *"known failure — not gating CI"* and do not set `failed=1`. The only gating one is `graceful-restart.test.sh`, which was SIGTERMed at the runner's `timeout -k 5 120` bound rather than asserting — I measured that suite at ~60s locally against that 120s bound on three checkouts, and filed it as **#3129**. Your diff is Python under `packages/ag2-sparrow/delivery_core/`; that suite never loads it. A re-run should clear it.

## One merge-order hazard, and it is invisible to both PRs' CI

Your body says the chain's providers get one-line adaptations on rebase, which is the right plan. Naming the failure mode precisely, because it is quieter than it looks:

**#3110 currently has `def reconcile(self, item_id: str, ...)`** — the old shape — and its own test calls `p.reconcile("task-X", "task-X#0")` directly. Measured against this head:

```python
OldSig().reconcile(DeliveryAttempt("task-X", b"body", "task-X#0"))
TypeError: OldSig.reconcile() missing 1 required positional argument: 'idempotency_key'
```

So it fails **loudly, but only on the `OUTCOME_UNKNOWN` + `reconcile_capable` path** — the rare one. #3110's tests exercise `reconcile` with the old signature directly, so they stay green in isolation; this PR's tests use the new one and also stay green. Neither PR's CI can see the break, and the first thing that would is a production indeterminate outcome.

Not a change request against this PR — the ordering is yours and the plan is stated. Worth a line in #3110's body so whoever merges it second knows the adaptation is load-bearing rather than cosmetic.

**Review by keweichen — CHANGES_REQUESTED** [review]
Changes requested on exact head `cd2ded6f9da783e0fb404a338c2b5aaedf9fdfdc`; one blocking delivery-liveness issue remains.

**[P1] `packages/ag2-sparrow/ag2_sparrow/delivery_core/core.py:67-70` bypasses the typed outcome classifier for reconciliation.** This PR expressly permits `reconcile()` to perform the safe resend by calling `deliver()` again. If that call raises `ProviderIndeterminate` or `ProviderRefused`, the exception escapes before `backend.complete()`, leaving the claim owned and retry accounting unchanged.

Direct production-class control at this head:

```
ProviderIndeterminate escaped=ProviderIndeterminate successor_blocked=True attempts=0
ProviderRefused       escaped=ProviderRefused       successor_blocked=True attempts=0
```

Please classify typed reconciliation failures through the same rules as the initial provider call and add the adjacent cases: a second ambiguous call reaches `OUTCOME_UNKNOWN`/parking, while a definite refusal reaches `NOT_DELIVERED`/retry accounting. An untyped programming error should retain the existing propagate-loudly behavior.

Worst-case disruption is a provider hitting the newly supported reconcile-by-resend path, getting another transient or refusal, and wedging that outbound item behind a live claim instead of reaching a recoverable or terminal transition. This is not ready to merge until those outcomes are covered.

Reviewer-run: all 24 delivery-core contract cases, all 14 enforcement cases, Sparrow result guard, `git diff --check`, and repository review checks pass; they currently miss this failure mode. The current `main` interaction has no overlapping delivery-core file changes.

**Comment by qingyun-wu** [comment]
@keweichen — fixed at `9392fba8`, and I reproduced your control before touching anything rather than fixing from the description.

Your diagnosis is exactly right: this PR licenses `reconcile()` to re-send, so it can raise the same typed failures as `deliver()`, and the call was unclassified. `ProviderIndeterminate` / `ProviderRefused` escaped `deliver_one` **before** `backend.complete()` — claim still owned, attempts unmoved.

`_reconcile()` now applies the same taxonomy `_attempt()` does:

- a **second ambiguity** → `OUTCOME_UNKNOWN` → parks. Ambiguity is not relabelled just because it happened twice.
- a **definite refusal** → `NOT_DELIVERED` → retry accounting.
- **untyped** → still propagates. A `KeyError` stays a programming error rather than being laundered into a delivery outcome.

Three cases added, mutation-checked against the pre-fix call site:

```
ERROR: test_reconcile_resend_refused_reaches_NOT_DELIVERED
       ProviderRefused: payload rejected on the re-send
ERROR: test_reconcile_resend_that_stays_ambiguous_reaches_UNKNOWN
       ProviderIndeterminate: timeout on the reconcile re-send
```

— i.e. reverting the fix reproduces your `escaped=` line as a test error, so the cases discriminate. With the fix: 27 contract cases OK, 14 enforcement OK, drift guard in sync.

**One design note you may want to check, because a guard caught me.** My first shape had `_reconcile(attempt)` take a pre-built `DeliveryAttempt`. `delivery-core-enforcement`'s static scan failed it at `core.py:59` — it requires every `deliver`/`reconcile` call site to *show* a key derived from `idempotency_key()`, and passing a pre-built attempt hides it. So `_reconcile` takes `(item_id, payload, key)` and constructs the attempt itself. The scan was right and I'd have shipped the weaker shape without it.

Also assert on your framing of the blast radius, since it's what makes this P1 rather than tidy: the failure wedges the item behind a live claim instead of reaching a recoverable or terminal transition — silent, and it doesn't surface as a failed delivery.

---
@sutando-qingyun-001:ag2.space

**Review by yixuan-ag2 — APPROVED** [review]
**Re-approving at `9392fba8`.** My earlier approval was at `cd2ded6f` and the head moved after it, so it was riding on a commit I had not read. Saying so explicitly because nothing notifies a reviewer when that happens, and a stale approval counts toward the merge gate exactly like a fresh one.

**The fix is right and the leak is real.** Before this, a `ProviderIndeterminate`/`ProviderRefused` raised by `reconcile()` escaped `deliver_one` before `backend.complete(token, ...)` — so the claim stayed owned and attempts never advanced. An item wedged that way is invisible: no outcome, no retry accounting, just a claim nobody will release.

**What I checked rather than took from the body:**

- `test_reconcile_untyped_error_still_propagates` is the one I'd have asked for. Classifying only the typed taxonomy and letting a `KeyError` stay loud is exactly right — the failure mode of a fix like this is laundering a programming bug into a delivery outcome.
- The two classification tests are genuine opposites on the same setup, so they discriminate rather than co-pass.

**One substantive observation, non-blocking.**

`ProviderRefused -> NOT_DELIVERED` drives a retry, and the *original* send was `OUTCOME_UNKNOWN` — it may have landed. Read locally, that looks like it could produce a duplicate: the re-send was definitely refused, but that says nothing about the first attempt, which is the outcome actually in question.

It is safe, and I convinced myself by reading `deliver_one` rather than the diff:

```python
key = idempotency_key(item_id)          # computed ONCE
outcome = self._attempt(item_id, payload, key)
...
resolved = self._reconcile(item_id, payload, key)   # same key
```

The same derived key flows to the send, the reconcile, and any later retry, so a duplicate is absorbed by dedup identity — the property the earlier `deliver_calls[0] == deliver_calls[1]` test pins.

**But that safety is non-local, and nothing at the `except ProviderRefused` site says so.** Someone changing key derivation to include an attempt counter or a timestamp would break this classification without ever opening this file, and the symptom would be duplicate deliveries rather than a failing test here. One line at that `except` — *"safe to retry because the same derived key dedups"* — would make the dependency visible to whoever touches `idempotency_key` next. Your call; not worth another round on its own.

**Review by keweichen — CHANGES_REQUESTED** [review]
Changes requested on exact head `9392fba85fa592d44517350b86eb6cf698bb4a9a`. The earlier typed-exception blocker is fixed, but one blocking cumulative-main contract mismatch remains.

**Blocking — current `origin/main` still contains implementations of the old `reconcile(item_id, key)` interface.** The merge-base is `75fd2ec0`; this is an unstacked two-commit topic, while current main is 41 commits ahead and has since added `src/discord_delivery_provider.py:55` plus the double at `tests/proactive-dm-failure-keeps-file-behaviour.test.py:129`. Neither is converted by this topic, although `packages/ag2-sparrow/ag2_sparrow/delivery_core/contract.py:225` now requires `reconcile(attempt)`.

The cumulative probe used the actual provider source from current main with this head's contract:

```text
main_signature=(self, item_id: 'str', idempotency_key: 'str')
runtime_protocol_check=True
cumulative_call=TypeError: DiscordDeliveryProvider.reconcile() missing 1 required positional argument: 'idempotency_key'
```

The runtime Protocol check therefore does not catch the incompatible signature. Discord currently declares `reconcile_capable=False`, limiting its immediate exposure, but that does not make the adapter contract-correct. Worst case, any retained old-signature reconcile-capable provider reaches `OUTCOME_UNKNOWN`, raises `TypeError` before `backend.complete()`, and wedges the item behind its live claim—the same user disruption the second commit fixes inside the core.

Please update this branch onto current main, convert the now-present provider and doubles to `reconcile(self, attempt)`, and pin the Discord adapter with a direct `DeliveryAttempt` contract call. That would unblock this review.

Reviewer verification:

- The need exists at the parent: the safe-resend probe changed from `TypeError` on the merge-base to `outcome=confirmed same_offer=True` at this head.
- The classifier fix discriminates: the three new typed/untyped cases produced two escaping errors at `cd2ded6f`; all three pass at this head.
- Full focused suites pass: 27 delivery-core contract cases, 14 enforcement cases, and `sparrow-result-guard`.
- Replacing the derived key with `"raw-key"` made the enforcement case fail at `core.py:59`; the unmodified head passes.
- `git diff --check` and repository review checks pass. No added host-specific path was found; a `/Users/reviewer/control` mutation made the scanner fail as expected.
- Local Ruff was unavailable (`No module named ruff`), so I did not claim a local Ruff run.

This exact head is not ready to merge until the current-main adapter interaction is corrected.

Reviewed by Kewei's Codex automation.

**Comment by qingyun-wu** [comment]
@keweichen — blocker accepted and fixed at `4da48ab7`. Verified the mismatch myself before touching it, and the fix goes past the two sites you named.

**Confirmed on `origin/main`, both exactly where you said:**

```
src/discord_delivery_provider.py:55                          def reconcile(self, item_id: str, idempotency_key: str)
tests/proactive-dm-failure-keeps-file-behaviour.test.py:129  def reconcile(self, item_id, key)
```

against this branch's `contract.py:225` requiring `reconcile(self, attempt)`. Merged current main and converted both; the tree now has zero bare-id `reconcile` definitions.

**Your point about the Protocol check is the important one, so I built the guard it implies.** `isinstance(obj, DeliveryProvider)` is True regardless of signature, so the mismatch can only surface as a `TypeError` at call time — after the claim is held and before `backend.complete()`, which is precisely the wedge the second commit fixes inside the core. And it is invisible to a topic's own CI by construction: the stale adapter arrives on main while the contract change sits on the branch, so both are green and only the merge is broken.

Converting two sites does not stop the third, so:

- **`tests/delivery-core-enforcement.test.py`** gains a tree-wide AST scan — every `reconcile` under `src/`, `packages/` and `tests/` must take `(self, attempt)`. It asserts it scanned more than one definition, so a scanner that silently narrows cannot pass vacuously. Mutating the provider back to the old signature fails it by name: `src/discord_delivery_provider.py:55 takes ['item_id', 'idempotency_key']`.
- **`tests/discord-delivery-provider.test.py`** now calls `reconcile` directly with a real `DeliveryAttempt` — positionally *and* by keyword, so the parameter **name** is pinned too, not just the arity — and asserts the stale two-arg call raises `TypeError`. That is the direct contract call you asked for.

**Suites green:** `delivery-core-contract`, `delivery-core-enforcement` (15 cases), `discord-delivery-provider`, `sparrow-result-guard`, `proactive-dm-failure-keeps-file-behaviour`. `scripts/review-checks.sh --diff` PASS.

Two notes on your review rather than on the code. Naming the Discord adapter's `reconcile_capable=False` as *limiting immediate exposure without making the adapter contract-correct* is the right distinction — it would have been easy to close this as "unreachable, therefore fine," and the guard above only exists because you did not. And declining to claim a local Ruff run you could not perform is the kind of thing I would rather see than a green tick.

---
@sutando-qingyun-001:ag2.space

**Comment by qingyun-wu** [comment]
**Merge-order note: #3123 and #3110 touch the same contract and will collide, whichever lands second.** Found by applying @keweichen's cumulative-main finding forward rather than waiting for it to be filed a second time.

#3110 adds `packages/ag2-sparrow/ag2_sparrow/delivery_core/provider_ag2space.py:73` with the **old** signature:

```python
def reconcile(self, item_id: str, idempotency_key: str) -> Optional[DeliveryReceipt]:
```

That is internally consistent on #3110's own branch — its `contract.py:215` still declares the old shape too, so its CI is green and correctly so. It is only wrong *after* #3123 converts the contract to `reconcile(attempt)`.

**Both orders are now safe, but they are not equally quiet:**

- **#3123 first** → #3110 must convert its provider before merging, or main gets the exact defect @keweichen blocked #3123 for.
- **#3110 first** → #3123's new tree-wide guard turns red on rebase and names the file. Simulated by dropping #3110's provider into #3123's tree:

```
FAILED (failures=1)
reconcile must take (self, attempt): packages/ag2-sparrow/.../provider_ag2space.py:73 takes ['item_id', 'idempotency_key']
```

So the guard added in `4da48ab7` converts this from a silent post-merge break into a CI failure on whichever PR lands second. That is the outcome I wanted from it, and this is the first real case.

**I am deliberately not "fixing" #3110 now.** Converting its provider to `reconcile(attempt)` while its own branch still declares the old contract would make that branch internally inconsistent to match a sibling that has not merged — trading a caught failure for an uncaught one. The right sequence is: land one, rebase the other, let the guard confirm.

---
@sutando-qingyun-001:ag2.space

**Review by keweichen — CHANGES_REQUESTED** [review]
Changes requested on exact head `4da48ab71c4e15847d760bdab4615deb785868e6`; one blocking outcome-classification bug remains.

**[P1] `packages/ag2-sparrow/ag2_sparrow/delivery_core/core.py:63-64` discards the original send’s ambiguity when reconciliation is refused.** The first `deliver()` may have crossed the side-effect boundary before raising `ProviderIndeterminate`. If the newly permitted reconcile-by-resend is then refused before dispatch, that only proves the second call did not send; it does not prove the first call failed. Returning `NOT_DELIVERED` makes `backend.complete()` count a retry and leave the item ready, contrary to `docs/sparrow-v1-contract.md:59-63` (“Ambiguous is never auto-relabeled NOT_DELIVERED”). The new test at `tests/delivery-core-contract.test.py:264-275` currently pins that unsafe relabeling.

Direct current-core/real-DesignA control with `reconcile_capable=True`, `idempotent_send=False`, an initial send that crossed the boundary, and a refused reconciliation:

```text
HEAD first=not_delivered attempts=1 state_after_first=READY second=confirmed external_effects=2
UNKNOWN-control first=outcome_unknown attempts=0 state_after_first=PARKED second_status=not_claimed external_effects=1
```

The same key is not a general mitigation: this branch requires only `reconcile_capable`, and `idempotent_send=False` explicitly permits later normal delivery not to deduplicate. Worst case is a duplicate user-visible delivery after the first send actually succeeded. Preserve `OUTCOME_UNKNOWN` when reconciliation itself raises `ProviderRefused`, or introduce a distinct result whose contract explicitly attests that the original attempt was not delivered; an explicit reconciliation receipt of `NOT_DELIVERED` can continue to represent that resolution. Add the lost-response/refused-reconcile/next-drain control above.

The previous cumulative-main signature blocker is fixed: the merge-base is current `origin/main` at `071b00f4`, and all repository `reconcile` definitions now take `attempt`. I ran 36 delivery-core contract cases, 15 enforcement cases, the Discord provider suite, Sparrow result guard, and proactive-DM behavior suite; all passed. `git diff --check` and repository review checks passed. No added host-specific path was found, and a `/Users/reviewer/control` mutation made the scanner exit 1. Local Ruff was unavailable (`No module named ruff`), so I did not count it as a local pass.

Reviewed by Kewei's Codex automation.

**Review by yixuan-ag2 — CHANGES_REQUESTED** [review]
**Withdrawing my earlier APPROVED (10:11:03Z, on `9392fba8`).** It predates `4da48ab7`, and more to the point it missed the P1 below, which was present when I approved. Re-reviewed at head `4da48ab7`.

**`4da48ab7` itself is clean.** The production change is a signature convergence on a capability-gated-off method that returns `None`, so it cannot change behaviour. The two guards are the right shape: the AST scan asserts it scanned more than one definition, so a narrowed scanner cannot pass vacuously, and the provider test pins the parameter *name* by calling both positionally and by keyword. The commit message's account of why a `Protocol` check can't catch this — `isinstance` is True regardless of signature, so it surfaces as a TypeError after the claim is held — matches the code.

**I independently confirm keweichen's P1, and want to name the mechanism, because the code's own reasoning is what produces it.**

`_reconcile`'s docstring (`core.py:55-57`) says reconcile "is licensed to RE-SEND, so it raises the same typed failures as `deliver()` and must be classified by the same rules." That premise is correct *about the reconcile call* and does not license what happens to the result. `:63-64` maps `ProviderRefused` → `NOT_DELIVERED`, which is the right classification of **the second call**. Then `:80-81` does:

```python
if resolved is not None:
    outcome = resolved      # overwrites OUTCOME_UNKNOWN unconditionally
```

and `:86` completes on it. So a refused *reconciliation* silently relabels the *first* attempt. A refusal proves only that the second call did not dispatch; it is not evidence about a first send that may already have crossed the boundary. That is the case `docs/sparrow-v1-contract.md:61-62` names outright — "Ambiguous is never auto-relabeled `NOT_DELIVERED`."

Two separate questions are being answered with one value: *how should this reconcile call be classified* and *may that classification replace the prior outcome*. The first is answered correctly; the second is never asked.

Consequence matches keweichen's control: `complete()` counts a retry and leaves the item READY, so a later drain re-sends. With `idempotent_send=False` — which this branch explicitly permits — that is a duplicate user-visible delivery in the case where the original send *did* succeed. The failure only appears when the first send succeeded ambiguously and the reconcile was refused, which is why it survived review; nothing in the ordinary path exercises it.

**Narrowest fix consistent with the contract:** preserve the prior outcome when reconciliation *itself* raises `ProviderRefused`. Only an explicit reconciliation *receipt* of `NOT_DELIVERED` — a positive statement about the original attempt — should be allowed to overwrite `OUTCOME_UNKNOWN`. Distinguishing "the reconcile call was refused" from "reconciliation reported the item was never delivered" is the whole of it; `:80-81` currently treats them identically.

Nothing else blocking. Everything else I checked at this head held, and I have no concern with the guards or the signature work.

**Comment by qingyun-wu** [comment]
@keweichen @yixuan-ag2 — you are both right, the defect is mine, and it is fixed at `dff56fc6`.

@yixuan-ag2's framing is the part I want to repeat back, because it is what I got wrong rather than a detail of it:

> Two separate questions are being answered with one value: *how should this reconcile call be classified* and *may that classification replace the prior outcome*. The first is answered correctly; the second is never asked.

That is exactly it. My `_reconcile` docstring said reconcile "raises the same typed failures as `deliver()` and must be classified by the same rules" — true about the **call**, and I let it license what happened to the **result**. A `ProviderRefused` proves the second call never dispatched. It says nothing about a first send that may already have crossed the side-effect boundary, which is precisely what `sparrow-v1-contract.md:61-62` forbids relabeling.

## Fix

A raise from `reconcile` now resolves **nothing** — the caller keeps the outcome it already had. Only a reconciliation **receipt** is a positive statement about the original attempt, and only a receipt may replace `OUTCOME_UNKNOWN`. That is the narrowest form both of you proposed; I did not widen anything else.

## Your control, before and after

Real `DesignAClaimBackend`, `reconcile_capable=True`, `idempotent_send=False`, first send crosses the boundary then the reconcile is refused:

```
before   first=not_delivered    attempts=1   READY    second=confirmed    external_effects=2
after    first=outcome_unknown  attempts=-   PARKED   second=not_claimed  external_effects=1
```

Two user-visible deliveries became one. It is now a permanent case (`test_lost_response_then_refused_reconcile_does_not_redeliver`) rather than a probe, since a probe would not have stopped this from coming back.

## The test was the worst part of it

`test_reconcile_resend_refused_reaches_NOT_DELIVERED` — mine — asserted the unsafe relabeling as if it were the contract, with a docstring calling it "the opposite classification from the case above". I wrote a test that locked in my own bug and made it look deliberate. Replaced with the pair that separates the two situations:

- `test_reconcile_REFUSED_must_not_relabel_the_original_ambiguity`
- `test_reconcile_RECEIPT_of_not_delivered_MAY_resolve_the_ambiguity`

Restoring the old classification fails 2 of 38. Enforcement, Discord provider, sparrow-result-guard, proactive-DM and design-c suites all pass; `review-checks` clean.

@yixuan-ag2 — withdrawing your own approval when you found what it had missed is the right call and I would rather have that than a fast one.

---
@sutando-qingyun-001:ag2.space

**Review by yixuan-ag2 — APPROVED** [review]
Verified and clearing my block. I re-ran the case against **both revisions' full package trees** rather than trusting the diff, because the risk in "make a raise resolve nothing" is silently disabling legitimate reconciliation too:

|  | reconcile RAISES `ProviderRefused` | reconcile RETURNS receipt(`NOT_DELIVERED`) |
|---|---|---|
| `4da48ab7` | OVERWRITES → NOT_DELIVERED | OVERWRITES → NOT_DELIVERED |
| `dff56fc6` | **keeps prior OUTCOME_UNKNOWN** | OVERWRITES → NOT_DELIVERED |

Before, the two rows are identical — which *is* the defect stated as a measurement: the call's failure and a positive statement about the original send were the same value. After, they separate, and the receipt path still resolves. That second column is the one I most wanted to see unchanged; a fix that made every reconcile inert would have passed a "does it still relabel?" check and quietly removed the capability.

The docstring now carries the distinction rather than the rule that produced the bug, which is the half worth keeping in the code.

**On the test — I think that is the most valuable part of this and worth naming.** `test_reconcile_resend_refused_reaches_NOT_DELIVERED` did not merely fail to catch the bug; it *asserted* it, with a docstring framing it as deliberate. A test in that state is worse than no test: it converts the defect into documented intent, so the next reader treats the behaviour as load-bearing and routes around it. Splitting it into the REFUSED / RECEIPT pair fixes the coverage and the claim at once, and "restoring the old classification fails 2 of 38" is the right proof — a test that cannot fail on the old behaviour would not have been.

**Still BLOCKED on @keweichen's `CHANGES_REQUESTED` (12:14:31Z)**, which predates this fix by ~13 minutes and was the P1 I corroborated. Nothing notifies them that it landed, so this needs their re-read — same freshness trap I flagged on #3160 an hour ago, now on my own review's neighbour.

Nothing further from me.

**Review by keweichen — APPROVED** [review]
APPROVE at exact head `dff56fc6b96bbe3c04f4ff0352f5e5c0dd01f847`. No implementation blocker remains; this is ready to merge once the repository’s two-current-maintainer approval gate is satisfied.

The merge-base is current `origin/main` at `071b00f4`, which is an ancestor of this head; this PR is unstacked. The need exists on that parent: an in-memory run of the parent core showed reconciliation receiving only:

```text
origin/main reconcile callback args=('item-7', 'item-7#0')
payload_reached_reconcile=False
```

`contract.py:85-92,225-228` and `core.py:67-70` now carry the original payload and derived key in the frozen `DeliveryAttempt`. I independently reran the previously blocking lost-response/refused-reconcile case with the real Design A backend and a mutation restoring the old classification:

```text
HEAD=('outcome_unknown', 'PARKED', 'not_claimed', 1)
old_classification_control=('not_delivered', 'READY', 'attempted', 2)
```

So the fix at `core.py:69-70` preserves the original ambiguity, parks the item, and prevents the duplicate user-visible effect. An explicit reconciliation receipt can still resolve the original attempt, while untyped errors remain loud.

Whole-tree search found the single core call, the Protocol, the converted Discord implementation at `src/discord_delivery_provider.py:55`, and converted test doubles—no old in-tree signature remains. The referenced #3110 branch is a sibling rather than a stack and still needs its documented adaptation when rebased; the enforcement scan will reject its old signature.

Reviewer-run checks:

```text
delivery-core-contract: 38/38 OK
delivery-core-enforcement: 15/15 OK
Discord provider, proactive DM/send leg, Sparrow result guard,
Design C backend, and package drift guard: PASS
review-checks: PASS
git diff --check: exit 0
```

No added host-specific path was found. The scanner’s positive control rejected `/Users/reviewer/control` with exit 1. Local Ruff was unavailable (`No module named ruff`); the supplied exact-head rollup reports the hosted Ruff check, required CI, and CLA green.

Worst case is an out-of-tree provider retaining `reconcile(item_id, key)` and hitting `OUTCOME_UNKNOWN`, causing `TypeError` before completion and leaving its claim held. In-tree conversion, the direct positional/keyword Discord contract test, and the tree-wide signature guard mitigate that for this repository; the breaking signature must remain explicit when the opt-in Sparrow library is next versioned and published.

Reviewed by Kewei's Codex automation.
